/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/catalog/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every attribute definition. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Definitions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: unknown[];
                        };
                    };
                };
                /** @description No session. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Define a new attribute.
         * @description The key is permanent. It becomes a Meilisearch filterable attribute, a public URL parameter, the discriminator on every stored value and an entry in variantAxes, so renaming would break bookmarked filter URLs and orphan the index.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        description?: string;
                        /**
                         * @default checkbox
                         * @enum {string}
                         */
                        filterUi?: "checkbox" | "swatch" | "range" | "toggle" | "select";
                        /** @default true */
                        isFilterable?: boolean;
                        /** @default false */
                        isSearchable?: boolean;
                        /** @default false */
                        isVariantAxis?: boolean;
                        key: string;
                        label: string;
                        /** @default [] */
                        options?: {
                            label: string;
                            /** @default 0 */
                            order?: number;
                            swatchHex?: string;
                            value: string;
                        }[];
                        /** @enum {string} */
                        type: "select" | "multiselect" | "text" | "number" | "boolean" | "color" | "dimension";
                        unit?: string;
                        /**
                         * @default {
                         *       "requiredByDefault": false
                         *     }
                         */
                        validation?: {
                            max?: number;
                            maxLength?: number;
                            min?: number;
                            /** @default false */
                            requiredByDefault?: boolean;
                            step?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                        };
                    };
                };
                /** @description Conflicts with something that already exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/attributes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit an attribute. Its key and type cannot change. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        description?: string;
                        /**
                         * @default checkbox
                         * @enum {string}
                         */
                        filterUi?: "checkbox" | "swatch" | "range" | "toggle" | "select";
                        /** @default true */
                        isFilterable?: boolean;
                        /** @default false */
                        isSearchable?: boolean;
                        /** @default false */
                        isVariantAxis?: boolean;
                        label?: string;
                        /** @default [] */
                        options?: {
                            label: string;
                            /** @default 0 */
                            order?: number;
                            swatchHex?: string;
                            value: string;
                        }[];
                        unit?: string;
                        /**
                         * @default {
                         *       "requiredByDefault": false
                         *     }
                         */
                        validation?: {
                            max?: number;
                            maxLength?: number;
                            min?: number;
                            /** @default false */
                            requiredByDefault?: boolean;
                            step?: number;
                        };
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: unknown;
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a category. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        description?: string;
                        imagePublicId?: string;
                        name: string;
                        /** @default 0 */
                        order?: number;
                        /** @default null */
                        parent?: string | null;
                        slug?: string;
                        /**
                         * @default active
                         * @enum {string}
                         */
                        status?: "active" | "hidden";
                        /**
                         * @default lenient
                         * @enum {string}
                         */
                        validationMode?: "lenient" | "strict";
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description Conflicts with something that already exists. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename or reconfigure a category. A slug change cascades to descendant paths. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        description?: string;
                        imagePublicId?: string;
                        name?: string;
                        /** @default 0 */
                        order?: number;
                        slug?: string;
                        /**
                         * @default active
                         * @enum {string}
                         */
                        status?: "active" | "hidden";
                        /**
                         * @default lenient
                         * @enum {string}
                         */
                        validationMode?: "lenient" | "strict";
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/catalog/categories/{id}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bind an attribute to a category. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        defId: string;
                        group?: string;
                        /** @default 0 */
                        order?: number;
                        /** @default false */
                        required?: boolean;
                    };
                };
            };
            responses: {
                /** @description Bound. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description The request was malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/categories/{id}/effective-attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every attribute that applies here, inherited ones included.
         * @description What the product form renders from. Each says which ancestor contributed it.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The effective set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                attributes: components["schemas"]["EffectiveAttribute"][];
                                categoryId: string;
                                categoryPath: string;
                                /** @enum {string} */
                                validationMode: "lenient" | "strict";
                            };
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/categories/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reparent a category.
         * @description Separate from PATCH because it rewrites the ancestry and path of every descendant and the denormalised categoryAncestors of every product beneath it, in one transaction.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        parent: string | null;
                    };
                };
            };
            responses: {
                /** @description Moved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description The request was malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/categories/{id}/suppressed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Drop inherited attributes on this branch. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        keys: string[];
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Category"];
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a product.
         * @description Attributes are sent flat — { roast: "medium", weight_g: 250 } — and validated at runtime against the category's effective set. Unknown keys are rejected. In lenient mode a missing required attribute is reported on the product rather than refused.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default {} */
                        attributes?: {
                            [key: string]: unknown;
                        };
                        categoryId: string;
                        description?: string;
                        /** @default [] */
                        images?: {
                            /** @default  */
                            alt?: string;
                            blurDataUrl?: string;
                            height?: number;
                            /** @default 0 */
                            position?: number;
                            publicId: string;
                            width?: number;
                        }[];
                        slug?: string;
                        /**
                         * @default draft
                         * @enum {string}
                         */
                        status?: "draft" | "active" | "archived";
                        subtitle?: string;
                        title: string;
                        /** @default [] */
                        variantAxes?: string[];
                        /** @default [] */
                        variants?: {
                            /** @default [] */
                            axisValues?: {
                                key: string;
                                value: string;
                            }[];
                            compareAtPrice?: {
                                amount: number;
                                currency: string;
                            };
                            /** @default [] */
                            imagePublicIds?: string[];
                            /** @default 0 */
                            position?: number;
                            price: {
                                amount: number;
                                currency: string;
                            };
                            sku?: string;
                            /**
                             * @default active
                             * @enum {string}
                             */
                            status?: "active" | "inactive";
                            /**
                             * @default {
                             *       "onHand": 0,
                             *       "lowStockThreshold": 3,
                             *       "backorderable": false
                             *     }
                             */
                            stock?: {
                                /** @default false */
                                backorderable?: boolean;
                                /** @default 3 */
                                lowStockThreshold?: number;
                                /** @default 0 */
                                onHand?: number;
                            };
                            weightGrams?: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Product"];
                        };
                    };
                };
                /** @description The request was malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description The body failed validation. */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit a product. */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @default {} */
                        attributes?: {
                            [key: string]: unknown;
                        };
                        description?: string;
                        /** @default [] */
                        images?: {
                            /** @default  */
                            alt?: string;
                            blurDataUrl?: string;
                            height?: number;
                            /** @default 0 */
                            position?: number;
                            publicId: string;
                            width?: number;
                        }[];
                        slug?: string;
                        /**
                         * @default draft
                         * @enum {string}
                         */
                        status?: "draft" | "active" | "archived";
                        subtitle?: string;
                        title?: string;
                        /** @default [] */
                        variantAxes?: string[];
                        /** @default [] */
                        variants?: {
                            /** @default [] */
                            axisValues?: {
                                key: string;
                                value: string;
                            }[];
                            compareAtPrice?: {
                                amount: number;
                                currency: string;
                            };
                            /** @default [] */
                            imagePublicIds?: string[];
                            /** @default 0 */
                            position?: number;
                            price: {
                                amount: number;
                                currency: string;
                            };
                            sku?: string;
                            /**
                             * @default active
                             * @enum {string}
                             */
                            status?: "active" | "inactive";
                            /**
                             * @default {
                             *       "onHand": 0,
                             *       "lowStockThreshold": 3,
                             *       "backorderable": false
                             *     }
                             */
                            stock?: {
                                /** @default false */
                                backorderable?: boolean;
                                /** @default 3 */
                                lowStockThreshold?: number;
                                /** @default 0 */
                                onHand?: number;
                            };
                            weightGrams?: number;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Product"];
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/admin/catalog/products/{id}/category": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a product to another category, re-validating against the destination. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        categoryId: string;
                    };
                };
            };
            responses: {
                /** @description Moved. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Product"];
                        };
                    };
                };
                /** @description The request was malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/products/{id}/variants/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate the variant grid from the chosen axes.
         * @description The cartesian product of the values the product actually offers, not the category's full option set. Warns at 24, refuses above 100. Send dryRun to see the count before anything is written; existing rows are matched by grid position so prices and stock already entered survive a regeneration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        axes: {
                            key: string;
                            values: string[];
                        }[];
                        /** @default false */
                        dryRun?: boolean;
                    };
                };
            };
            responses: {
                /** @description The plan, or the updated product. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                count: number;
                                warn: boolean;
                            };
                        };
                    };
                };
                /** @description The request was malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The active category tree, flat and root-first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Every active category. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Category"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/categories/by-path/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One category, with the filter panel generated from its attributes. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    path: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The category and its generated filters. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                category: {
                                    /** @description Root-first, including self. */
                                    ancestors: string[];
                                    description?: string;
                                    name: string;
                                    /** @example coffee-tea/beans */
                                    path: string;
                                    slug: string;
                                };
                                filters: components["schemas"]["CategoryFilter"][];
                            };
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Degraded product listing. Meilisearch serves this on the storefront.
         * @description Keyset pagination, never .skip(n). Page size defaults to 24 and is capped at 60. Returns `page.degraded: true` so a caller can tell this apart from the search path.
         */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    cursor?: string;
                    in_stock?: boolean;
                    per_page?: number;
                    sort?: "newest" | "price_asc" | "price_desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of product cards. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ProductCard"][];
                            page: {
                                degraded: boolean;
                                hasMore: boolean;
                                nextCursor: string | null;
                                perPage: number;
                            };
                        };
                    };
                };
                /** @description The request was malformed. */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One product, with its attributes and variants. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The product. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Product"];
                        };
                    };
                };
                /** @description Not found, or not visible to this caller. */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AttributeOption: {
            label: string;
            order: number;
            swatchHex?: string;
            value: string;
        };
        Category: {
            _id: string;
            /** @description Root-first, including self. */
            ancestors: string[];
            depth: number;
            description?: string;
            imagePublicId?: string;
            name: string;
            order: number;
            parent: string | null;
            /** @example coffee-tea/beans */
            path: string;
            slug: string;
        };
        /** @description One filter in the storefront panel, generated from an admin-defined attribute. The frontend has no hardcoded knowledge of any of these. */
        CategoryFilter: {
            /** @enum {string} */
            filterUi: "checkbox" | "swatch" | "range" | "toggle" | "select";
            key: string;
            label: string;
            options: components["schemas"]["AttributeOption"][];
            /** @enum {string} */
            type: "select" | "multiselect" | "text" | "number" | "boolean" | "color" | "dimension";
            unit?: string;
        };
        EffectiveAttribute: {
            defId: string;
            description?: string;
            /** @enum {string} */
            filterUi: "checkbox" | "swatch" | "range" | "toggle" | "select";
            group?: string;
            inheritedFrom: {
                id: string;
                name: string;
            } | null;
            isAxisEligible: boolean;
            isFilterable: boolean;
            isSearchable: boolean;
            key: string;
            label: string;
            options: components["schemas"]["AttributeOption"][];
            order: number;
            required: boolean;
            /** @enum {string} */
            type: "select" | "multiselect" | "text" | "number" | "boolean" | "color" | "dimension";
            unit?: string;
            validation: {
                max?: number;
                maxLength?: number;
                min?: number;
                step?: number;
            };
        };
        Error: {
            error: {
                /** @example NOT_FOUND */
                code: string;
                details?: unknown;
                message: string;
                requestId: string;
            };
        };
        Money: {
            /** @description Minor units. 1999 is $19.99. */
            amount: number;
            currency: string;
        };
        Product: components["schemas"]["ProductCard"] & {
            attributes: components["schemas"]["ProductAttribute"][];
            category: string;
            categoryAncestors: string[];
            defaultVariantId?: string;
            description?: string;
            /** @enum {string} */
            status: "draft" | "active" | "archived";
            variantAxes: string[];
            variants: components["schemas"]["Variant"][];
        };
        ProductAttribute: {
            /** @description Rendered at write time, so the spec table needs no lookup. */
            displayValue: string;
            group?: string;
            key: string;
            order: number;
            /** @enum {string} */
            type: "select" | "multiselect" | "text" | "number" | "boolean" | "color" | "dimension";
            unit?: string;
            valueBool?: boolean;
            valueDim?: {
                height: number;
                length: number;
                unit: string;
                width: number;
            };
            valueNumber?: number;
            valueString?: string;
            valueStrings?: string[];
        };
        ProductCard: {
            _id: string;
            images: {
                alt: string;
                blurDataUrl?: string;
                height?: number;
                position: number;
                publicId: string;
                width?: number;
            }[];
            inStock: boolean;
            priceRange?: {
                currency: string;
                max: number;
                min: number;
            };
            ratingAverage: number;
            ratingCount: number;
            slug: string;
            subtitle?: string;
            title: string;
        };
        Variant: {
            _id: string;
            axisValues: {
                key: string;
                value: string;
            }[];
            compareAtPrice?: components["schemas"]["Money"];
            imagePublicIds: string[];
            position: number;
            price: components["schemas"]["Money"];
            sku: string;
            /** @enum {string} */
            status: "active" | "inactive";
            stock: {
                available: number;
                backorderable: boolean;
                lowStockThreshold: number;
                onHand: number;
                reserved: number;
            };
            weightGrams?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAttributeOption = components['schemas']['AttributeOption'];
export type SchemaCategory = components['schemas']['Category'];
export type SchemaCategoryFilter = components['schemas']['CategoryFilter'];
export type SchemaEffectiveAttribute = components['schemas']['EffectiveAttribute'];
export type SchemaError = components['schemas']['Error'];
export type SchemaMoney = components['schemas']['Money'];
export type SchemaProduct = components['schemas']['Product'];
export type SchemaProductAttribute = components['schemas']['ProductAttribute'];
export type SchemaProductCard = components['schemas']['ProductCard'];
export type SchemaVariant = components['schemas']['Variant'];
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
